# Generated by Django 5.1.1 on 2024-10-07 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mugiwara', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='despesa',
            old_name='fornecedor',
            new_name='fornecedor_id',
        ),
        migrations.RenameField(
            model_name='extrato_bancario',
            old_name='conta_bancaria',
            new_name='conta_bancaria_id',
        ),
        migrations.RenameField(
            model_name='pagamento',
            old_name='conta_bancaria',
            new_name='conta_bancaria_id',
        ),
        migrations.RenameField(
            model_name='pagamento',
            old_name='despesa',
            new_name='despesa_id',
        ),
        migrations.RenameField(
            model_name='recebimento',
            old_name='receita',
            new_name='receita_id',
        ),
        migrations.RenameField(
            model_name='receita',
            old_name='cliente',
            new_name='cliente_id',
        ),
    ]
