# Generated by Django 5.1.1 on 2024-10-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mugiwara', '0002_rename_fornecedor_despesa_fornecedor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='status',
            field=models.IntegerField(choices=[(1, 'Em Aberto'), (2, 'Pago')], default=1),
        ),
        migrations.AddField(
            model_name='receita',
            name='status',
            field=models.IntegerField(choices=[(1, 'Em Aberto'), (2, 'Pago')], default=1),
        ),
    ]
