# Generated by Django 5.1.1 on 2024-10-10 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mugiwara', '0003_despesa_status_receita_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='cliente_id',
        ),
        migrations.RemoveField(
            model_name='extrato_bancario',
            name='conta_bancaria_id',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='fornecedor_id',
        ),
        migrations.DeleteModel(
            name='usuario',
        ),
        migrations.AddField(
            model_name='recebimento',
            name='conta_bancaria_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mugiwara.conta_bancaria'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='categoria',
            field=models.IntegerField(choices=[(1, 'Categoria 1'), (2, 'Categoria 2'), (3, 'Categoria 3'), (4, 'Categoria 4')], default=1),
        ),
        migrations.AlterField(
            model_name='receita',
            name='categoria',
            field=models.IntegerField(choices=[(1, 'Categoria 1'), (2, 'Categoria 2'), (3, 'Categoria 3'), (4, 'Categoria 4')], default=1),
        ),
        migrations.DeleteModel(
            name='cliente',
        ),
        migrations.DeleteModel(
            name='extrato_bancario',
        ),
        migrations.DeleteModel(
            name='fornecedor',
        ),
    ]
