# Generated by Django 5.1.1 on 2024-10-14 01:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mugiwara', '0004_remove_receita_cliente_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fluxo_caixa',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='fluxo_caixa',
            old_name='data',
            new_name='data_final',
        ),
        migrations.RemoveField(
            model_name='fluxo_caixa',
            name='projecao_entradas',
        ),
        migrations.RemoveField(
            model_name='fluxo_caixa',
            name='projecao_saidas',
        ),
        migrations.AddField(
            model_name='fluxo_caixa',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fluxo_caixa',
            name='data_inicial',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conta_bancaria',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='conta_bancaria',
            name='updated_at',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
