# Generated by Django 5.1.1 on 2024-10-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mugiwara', '0005_alter_fluxo_caixa_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conta_bancaria',
            options={'ordering': ['nome_banco', '-created_at']},
        ),
        migrations.AlterField(
            model_name='conta_bancaria',
            name='saldo_atual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
