# Generated by Django 5.1.1 on 2024-10-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mugiwara', '0006_alter_conta_bancaria_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta_bancaria',
            name='saldo_atual',
            field=models.DecimalField(auto_created=True, decimal_places=2, default=0, max_digits=9),
        ),
    ]
