# Generated by Django 5.1.1 on 2024-10-15 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mugiwara', '0007_alter_conta_bancaria_saldo_atual'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conta_bancaria',
            options={'ordering': ['-created_at', 'nome_banco']},
        ),
    ]
