# Generated by Django 5.1.1 on 2024-10-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mugiwara', '0008_alter_conta_bancaria_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conta_bancaria',
            options={'ordering': ['id', '-created_at', 'nome_banco']},
        ),
        migrations.AlterField(
            model_name='fluxo_caixa',
            name='data_final',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fluxo_caixa',
            name='data_inicial',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fluxo_caixa',
            name='saldo_final',
            field=models.DecimalField(auto_created=True, decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='fluxo_caixa',
            name='saldo_inicial',
            field=models.DecimalField(auto_created=True, decimal_places=2, max_digits=9),
        ),
    ]
