# Generated by Django 5.1.1 on 2024-10-15 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mugiwara', '0009_alter_conta_bancaria_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fluxo_caixa',
            name='saldo_final',
        ),
        migrations.RemoveField(
            model_name='fluxo_caixa',
            name='saldo_inicial',
        ),
    ]
