# Generated by Django 5.1.1 on 2024-10-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mugiwara', '0010_remove_fluxo_caixa_saldo_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='valor_pago',
            field=models.DecimalField(auto_created=True, decimal_places=2, max_digits=9),
        ),
    ]
